// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQcguH6zh-Q8mG9KHFIkoqwt-3wn9-cVs',
    appId: '1:1064301233691:web:0024397e882f96d9579abe',
    messagingSenderId: '1064301233691',
    projectId: 'auth-9ca42',
    authDomain: 'auth-9ca42.firebaseapp.com',
    databaseURL: 'https://auth-9ca42-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-9ca42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbbXjvzAYS6MxvnhxAmVhnwdBGcdhHIrM',
    appId: '1:1064301233691:android:85f872b530deb368579abe',
    messagingSenderId: '1064301233691',
    projectId: 'auth-9ca42',
    databaseURL: 'https://auth-9ca42-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-9ca42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJl573sF_Kbq7dw3BqUhw3ztkquIjZY08',
    appId: '1:1064301233691:ios:e17851904df604bd579abe',
    messagingSenderId: '1064301233691',
    projectId: 'auth-9ca42',
    databaseURL: 'https://auth-9ca42-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-9ca42.appspot.com',
    iosClientId: '1064301233691-7sg9hop1iu2qmhnvin5c37rects1vilh.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJl573sF_Kbq7dw3BqUhw3ztkquIjZY08',
    appId: '1:1064301233691:ios:e17851904df604bd579abe',
    messagingSenderId: '1064301233691',
    projectId: 'auth-9ca42',
    databaseURL: 'https://auth-9ca42-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-9ca42.appspot.com',
    iosClientId: '1064301233691-7sg9hop1iu2qmhnvin5c37rects1vilh.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );
}
